### PR TITLE
Cldfbench support

### PR DESCRIPTION
**Pull request by johenglisch**

### CODE REVIEW

**Comment by xrotwang** [comment]
@johenglisch merging this would require merging the cldfbench branches of all repos and recreating the prod db from these, right?

**Comment by johenglisch** [comment]
No, that is not needed.  The `contributions.json` file is set up, so that `clld initdb` checks out the `cldfbench` branch after cloning the data repos.

**Comment by johenglisch** [comment]
So, we can merge later (and/or create a new release on Zenodo and point `contribution.json` to the DOIs)

**Comment by xrotwang** [comment]
ah, ok. But we would want the `cldfbench`  branch to be the deafult branch in the future, I guess? E.g. to make sure we always make releases from it?

**Comment by xrotwang** [comment]
Ah, ok. I think I understand. We'd only switch `contributions.json` to use the default branch after the merge, right?

**Comment by johenglisch** [comment]
Japp

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
